### ISSUE TITLE
Problem when using pure linux threads with C++

### ISSUE THREAD

**Issue by hnanhtuan** [skeeto/pure-linux-threads-demo#3]
Hi,

I want to call an ASM function from C++. In the ASM function, I want to create some child threads.
I adopt your x64 assembly code by replacing the **_start** label (line [3](https://github.com/skeeto/pure-linux-threads-demo/blob/a1ffd9ef8b4ba6e65b10002f94e94bdcaaaa11cf/threads-x86_64.s#L3) and [44](https://github.com/skeeto/pure-linux-threads-demo/blob/a1ffd9ef8b4ba6e65b10002f94e94bdcaaaa11cf/threads-x86_64.s#L44)) by **demo**. 
The main.cpp file for calling the assembly **demo** function and the Makefile are as below.

However, I got the **"Segmentation fault (core dumped)"**. 
Your provided code (only x64 assembly) works perfectly without any error.

Do you notice any problem in my code? Or any suggestion to fix the issue?
Thank you very much.

Here is the main.cpp:
`#include <bits/stdc++.h>
#include <ostream>

using namespace std;

extern "C" int demo(void);

int main(){
    demo();
    return 0;
}`

And Makefile
`CFLAGS = -std=c++11 -Wall
OBJS = thread_asm.o

runme: main.cpp $(OBJS)
	g++ $(CFLAGS) main.cpp *.o -o runme

thread_asm.o: thread.asm
	nasm -f elf64  thread.asm -o thread_asm.o	

clean: 
	rm -r runme *.o`

**Comment by hnanhtuan** [comment]
Actually, the system call sys_mmap does not ignore the last two arguments in this case. I need to set R8 and R9 to 0 to have the code work.

Thank you for your code anyway.

**Comment by skeeto** [comment]
I've gotten a similar report before about those last two arguments. 
These two arguments definitely used to be ignored, and the old man pages 
say so, but the Linux kernel behavior changed at some point.
